Working on Identity
Most of the way finished with the first part of the document - I think.
Added User.cs
Added Role.cs
These are empty as of right now

Running this commit will result in the following error:
System.InvalidOperationException: 'AddEntityFrameworkStores can only be called with a user that derives from IdentityUser<TKey>.'

I have a lead on the solution - will likely work more after a few minutes break.